### PR TITLE
[no refs]: conflicts with 'become' and 'delegate_to' methods

### PR DESCRIPTION
**Pull request by x21Kenobi**
Users may not be the same on controller and remote nodes.
So, if you don't have the same of it, you may run into errors like the follow:

```
fatal: [default]: FAILED! => {
    "changed": false,
    "module_stderr": "Sorry, try again.\n[sudo via ansible, key=random_casual_miao] password:\nsudo: 1 incorrect password attempt\n",",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
The commit solves this problem and can be considered as a patch level

### CODE REVIEW

**Comment by MonolithProjects** [comment]
Hi there. I guess the better solution would be to add `become: false` to the tasks with `delegate_to: localhost`. Basically there is no need to escalate the privileges.

**Comment by x21Kenobi** [comment]
For example, image to run a playbook on a workstation that need privileges to launch some commands: if you set `become: false`, the playbook may fails.
I tell you this because I have such a situation, but feel free to evaluate the commit as you see fit.

**Comment by x21Kenobi** [comment]
Also, I think it's better run all tasks on remote: in this case, I see no reason to use the `delegate_to` method.

**Comment by MonolithProjects** [comment]
Even if the playbook is running with escalated privileges, you can set specific task to not to use `sudo`. I mean the solution could look like this:
```
- name: Download runner package version - "{{ runner_version }}" (RUN ONCE)
  get_url:
    url: "https://github.com/actions/runner/releases/download/v{{ runner_version }}/actions-runner-linux-x64-{{ runner_version }}.tar.gz"
    dest: "./actions-runner-linux-{{ runner_version }}.tar.gz"
    force: no
  run_once: yes
  become: false
  delegate_to: localhost
  tags:
    - install
```

For the `delegate_to`, well the idea behind this was to not to download the package from the internet 10 times if you have 10 runners. Rather the package is downloaded once to the local host and distributed to the remote hosts from there. But yah maybe it is adding some additional overhead to the whole role and i may change it in the future.

**Comment by x21Kenobi** [comment]
I understand, so I'll try with `become: false`

**Comment by x21Kenobi** [comment]
It's work!

**Comment by x21Kenobi** [comment]
sorry for all these "force-pushed", typing errors as you can see

**Comment by MonolithProjects** [comment]
No problem at all. Thanks for your help. The new release `1.2.6` with your fix is already in the [Ansible Galaxy](https://galaxy.ansible.com/monolithprojects/github_actions_runner)

**Pull request merged**
